package com.eloan.base.mapper;


import com.eloan.base.domain.IpLog;

import java.util.List;

public interface IpLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IpLog
     *
     * @mbggenerated Wed Dec 28 22:20:50 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IpLog
     *
     * @mbggenerated Wed Dec 28 22:20:50 CST 2016
     */
    int insert(IpLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IpLog
     *
     * @mbggenerated Wed Dec 28 22:20:50 CST 2016
     */
    IpLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IpLog
     *
     * @mbggenerated Wed Dec 28 22:20:50 CST 2016
     */
    List<IpLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IpLog
     *
     * @mbggenerated Wed Dec 28 22:20:50 CST 2016
     */
    int updateByPrimaryKey(IpLog record);
}