package com.eloan.base.mapper;


import com.eloan.base.domain.SystemDictionaryItem;
import com.eloan.base.query.SystemDictionaryQueryObject;

import java.util.List;

public interface SystemdictionaryitemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SystemDictionaryItem
     *
     * @mbggenerated Tue Dec 27 17:58:30 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SystemDictionaryItem
     *
     * @mbggenerated Tue Dec 27 17:58:30 CST 2016
     */
    int insert(SystemDictionaryItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SystemDictionaryItem
     *
     * @mbggenerated Tue Dec 27 17:58:30 CST 2016
     */
    SystemDictionaryItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SystemDictionaryItem
     *
     * @mbggenerated Tue Dec 27 17:58:30 CST 2016
     */
    List<SystemDictionaryItem> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SystemDictionaryItem
     *
     * @mbggenerated Tue Dec 27 17:58:30 CST 2016
     */
    int updateByPrimaryKey(SystemDictionaryItem record);

    /**
     * 根据title和parentId查询
     * @param qo
     * @return
     */
    List<SystemDictionaryItem> selectByTitleAndParentId(SystemDictionaryQueryObject qo);
}