package com.eloan.business.mapper;

import com.eloan.business.domain.Realauth;
import java.util.List;

public interface RealauthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realauth
     *
     * @mbggenerated Tue Jan 03 15:07:59 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realauth
     *
     * @mbggenerated Tue Jan 03 15:07:59 CST 2017
     */
    int insert(Realauth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realauth
     *
     * @mbggenerated Tue Jan 03 15:07:59 CST 2017
     */
    Realauth selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realauth
     *
     * @mbggenerated Tue Jan 03 15:07:59 CST 2017
     */
    List<Realauth> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realauth
     *
     * @mbggenerated Tue Jan 03 15:07:59 CST 2017
     */
    int updateByPrimaryKey(Realauth record);
}