package com.eloan.business.mapper;


import com.eloan.business.domain.Userinfo;

import java.util.List;

public interface UserinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Tue Dec 27 17:44:04 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Tue Dec 27 17:44:04 CST 2016
     */
    int insert(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Tue Dec 27 17:44:04 CST 2016
     */
    Userinfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Tue Dec 27 17:44:04 CST 2016
     */
    List<Userinfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Tue Dec 27 17:44:04 CST 2016
     */
    int updateByPrimaryKey(Userinfo record);
}