package com.eloan.business.mapper;

import com.eloan.business.domain.Vedioauth;
import com.eloan.business.query.VedioAuthQueryObject;

import java.util.List;

public interface VedioauthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedioauth
     *
     * @mbggenerated Wed Jan 04 16:58:52 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedioauth
     *
     * @mbggenerated Wed Jan 04 16:58:52 CST 2017
     */
    int insert(Vedioauth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedioauth
     *
     * @mbggenerated Wed Jan 04 16:58:52 CST 2017
     */
    Vedioauth selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedioauth
     *
     * @mbggenerated Wed Jan 04 16:58:52 CST 2017
     */
    List<Vedioauth> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vedioauth
     *
     * @mbggenerated Wed Jan 04 16:58:52 CST 2017
     */
    int updateByPrimaryKey(Vedioauth record);

    /**
     * 根据时间和用户名查询
     * @param qo
     * @return
     */
    List<Vedioauth> query(VedioAuthQueryObject qo);
}